"""
csp.py — Constraint Satisfaction Problem with AC-3 Arc Consistency

Finds safe operating points satisfying inter-variable constraints.

Inter-variable constraints:
  1. Q >= 80% of heat generated by reaction (energy balance)
  2. Steady-state conversion >= 70% (quality constraint)
  3. T <= 500 K (safety)
  4. F*(1+R) <= 20 L/min (equipment limit)

AC-3 preprocesses domains via arc-consistency before backtracking.
MRV (Minimum Remaining Values) heuristic selects the most constrained
variable first during backtracking.
"""

import numpy as np
from collections import deque


class CSP:
    """
    CSP for safe operating point selection.
    AC-3 arc-consistency preprocessing + backtracking with MRV heuristic.
    """

    CA0   = 1.0
    k     = 0.15
    deltaH = -5000
    rhoCp = 500
    V     = 100

    def __init__(self):
        self.variables = ["T", "F", "Q", "R"]  # temp, flow, cooling, recycle ratio
        self.domains = {
            "T": list(range(380, 501, 10)),
            "F": list(range(2, 11)),
            "Q": list(range(1000, 5001, 250)),
            "R": [round(x, 2) for x in np.arange(0.0, 2.1, 0.25)],
        }
        self.binary_constraints = [
            ("Q", "F", lambda q, f: q >= self._min_cooling(f)),
            ("T", "F", lambda t, f: self._ss_conversion(t, f) >= 0.70),
            ("T", "Q", lambda t, q: t <= 500),
            ("F", "R", lambda f, r: f * (1 + r) <= 20),
        ]

    def _min_cooling(self, F):
        CA_ss = self.CA0 * F / (F + self.k * self.V)
        Q_gen = (-self.deltaH / self.rhoCp) * self.k * CA_ss * self.V
        return max(0, Q_gen * 0.8)

    def _ss_conversion(self, T, F):
        CA_ss = self.CA0 * F / (F + self.k * self.V)
        return 1 - CA_ss / self.CA0

    def _revise(self, xi, xj, fn):
        revised, to_rm = False, []
        for vi in self.domains[xi]:
            if not any(fn(vi, vj) for vj in self.domains[xj]):
                to_rm.append(vi)
                revised = True
        for v in to_rm:
            self.domains[xi].remove(v)
        return revised

    def ac3(self):
        """AC-3: enforce arc consistency across all binary constraints."""
        queue = deque()
        for xi, xj, fn in self.binary_constraints:
            queue.append((xi, xj, fn))
            queue.append((xj, xi, lambda vj, vi, f=fn: f(vi, vj)))
        while queue:
            xi, xj, fn = queue.popleft()
            if self._revise(xi, xj, fn):
                if not self.domains[xi]:
                    return False
                for xk, xl, gn in self.binary_constraints:
                    if xl == xi and xk != xj:
                        queue.append((xk, xi, gn))
        return True

    def consistent(self, assignment):
        for xi, xj, fn in self.binary_constraints:
            if xi in assignment and xj in assignment:
                if not fn(assignment[xi], assignment[xj]):
                    return False
        return True

    def backtrack(self, assignment=None):
        if assignment is None:
            assignment = {}
        if len(assignment) == len(self.variables):
            return dict(assignment)
        unassigned = [v for v in self.variables if v not in assignment]
        var = min(unassigned, key=lambda v: len(self.domains[v]))  # MRV
        for value in self.domains[var]:
            assignment[var] = value
            if self.consistent(assignment):
                result = self.backtrack(assignment)
                if result is not None:
                    return result
            del assignment[var]
        return None

    def solve(self):
        """Return the first feasible solution and a status message."""
        feasible = self.ac3()
        if not feasible:
            return None, "Infeasible"
        sol = self.backtrack()
        return sol, "AC-3 pruned domains; backtracking found solution"

    def get_all_solutions(self, max_n=30):
        """Return up to max_n feasible solutions."""
        solutions = []
        self.ac3()

        def bt(asgn):
            if len(solutions) >= max_n:
                return
            if len(asgn) == len(self.variables):
                solutions.append(dict(asgn))
                return
            unassigned = [v for v in self.variables if v not in asgn]
            var = min(unassigned, key=lambda v: len(self.domains[v]))
            for val in self.domains[var]:
                asgn[var] = val
                if self.consistent(asgn):
                    bt(asgn)
                del asgn[var]

        bt({})
        return solutions


if __name__ == "__main__":
    csp = CSP()
    solution, msg = csp.solve()
    print("Status  :", msg)
    print("Solution:", solution)

    csp2 = CSP()
    all_solutions = csp2.get_all_solutions(30)
    print(f"Total feasible solutions found: {len(all_solutions)}")
